export type FeatureStudioItem = {
  id: string
  title: string
  category: string
  description: string
}

export const featureStudioItems: FeatureStudioItem[] = [
  { id: 'fs-001', title: 'ICP Snapshot Builder', category: 'Strategy', description: 'Capture ideal customer profile assumptions in one reusable brief.' },
  { id: 'fs-002', title: 'Niche Offer Angle Mapper', category: 'Strategy', description: 'Map primary and backup offer angles per niche.' },
  { id: 'fs-003', title: 'Category Entry Prioritizer', category: 'Strategy', description: 'Rank expansion categories by speed-to-revenue and complexity.' },
  { id: 'fs-004', title: 'Competitive Position Grid', category: 'Strategy', description: 'Visualize positioning overlap against key market competitors.' },
  { id: 'fs-005', title: 'Service Packaging Matrix', category: 'Strategy', description: 'Design offer tiers with margin and effort scoring.' },
  { id: 'fs-006', title: 'Channel Readiness Checklist', category: 'Strategy', description: 'Assess if each channel is ready for paid scale.' },
  { id: 'fs-007', title: 'Demand Capture Heatmap', category: 'Strategy', description: 'Plot where high-intent traffic currently leaks.' },
  { id: 'fs-008', title: 'Stakeholder Alignment Board', category: 'Strategy', description: 'Keep client owners and deliverables aligned before launch.' },
  { id: 'fs-009', title: 'Growth Hypothesis Register', category: 'Strategy', description: 'Track, test, and retire growth hypotheses by outcome.' },
  { id: 'fs-010', title: 'Quarterly Priority Ladder', category: 'Strategy', description: 'Stack-rank quarterly growth priorities by impact.' },

  { id: 'fs-011', title: 'Lead Source Quality Ladder', category: 'Acquisition', description: 'Compare source quality by qualification and close rate.' },
  { id: 'fs-012', title: 'Campaign Spin-Up Tracker', category: 'Acquisition', description: 'Track campaign setup readiness and blockers.' },
  { id: 'fs-013', title: 'Audience Segment Profiler', category: 'Acquisition', description: 'Define acquisition audience segments and messaging hooks.' },
  { id: 'fs-014', title: 'Ad Creative Rotation Planner', category: 'Acquisition', description: 'Schedule refresh cycles for top-performing ads.' },
  { id: 'fs-015', title: 'Cold Outreach Target Queue', category: 'Acquisition', description: 'Queue outbound target lists with next-best actions.' },
  { id: 'fs-016', title: 'Partnership Prospect Board', category: 'Acquisition', description: 'Track referral and co-marketing partner opportunities.' },
  { id: 'fs-017', title: 'Lead Magnet Performance Hub', category: 'Acquisition', description: 'Measure opt-in assets by quality and conversion.' },
  { id: 'fs-018', title: 'Webinar Funnel Planner', category: 'Acquisition', description: 'Plan registration-to-follow-up webinar journeys.' },
  { id: 'fs-019', title: 'Event Pipeline Capture Tool', category: 'Acquisition', description: 'Capture and qualify conference/event sourced leads.' },
  { id: 'fs-020', title: 'UTM Hygiene Monitor', category: 'Acquisition', description: 'Detect tracking gaps in UTM tagging and naming.' },

  { id: 'fs-021', title: 'Landing Page Hook Tester', category: 'Conversion', description: 'Compare opening hooks by conversion objective.' },
  { id: 'fs-022', title: 'Form Friction Detector', category: 'Conversion', description: 'Flag fields and steps causing form abandonment.' },
  { id: 'fs-023', title: 'CTA Intent Matching Lab', category: 'Conversion', description: 'Test CTA variants against visitor intent segments.' },
  { id: 'fs-024', title: 'Social Proof Placement Planner', category: 'Conversion', description: 'Place trust elements based on stage-specific objections.' },
  { id: 'fs-025', title: 'Offer Stack Optimizer', category: 'Conversion', description: 'Tune offer components for higher acceptance rates.' },
  { id: 'fs-026', title: 'Guarantee Clarity Scorer', category: 'Conversion', description: 'Score and improve risk-reversal messaging clarity.' },
  { id: 'fs-027', title: 'Pricing Table Experimenter', category: 'Conversion', description: 'Run pricing presentation tests safely.' },
  { id: 'fs-028', title: 'Checkout Drop-Off Analyzer', category: 'Conversion', description: 'Identify and fix conversion loss in checkout flow.' },
  { id: 'fs-029', title: 'Micro-Conversion Trigger Set', category: 'Conversion', description: 'Deploy soft conversion prompts before hard asks.' },
  { id: 'fs-030', title: 'Session Replay Insight Board', category: 'Conversion', description: 'Aggregate usability insights from behavior reviews.' },

  { id: 'fs-031', title: 'MQL-to-SQL Transition Watch', category: 'Pipeline', description: 'Monitor progression quality from marketing to sales.' },
  { id: 'fs-032', title: 'Pipeline Stage Exit Alerts', category: 'Pipeline', description: 'Alert on stage stagnation and aging risk.' },
  { id: 'fs-033', title: 'Lead Aging Intervention Queue', category: 'Pipeline', description: 'Surface leads requiring immediate intervention.' },
  { id: 'fs-034', title: 'SLA Breach Notifier', category: 'Pipeline', description: 'Track first-response and follow-up SLA misses.' },
  { id: 'fs-035', title: 'Deal Momentum Scoring', category: 'Pipeline', description: 'Score pipeline momentum based on activity and recency.' },
  { id: 'fs-036', title: 'Opportunity Confidence Meter', category: 'Pipeline', description: 'Estimate win confidence per opportunity.' },
  { id: 'fs-037', title: 'Reactivation Cadence Builder', category: 'Pipeline', description: 'Build revive sequences for stale opportunities.' },
  { id: 'fs-038', title: 'Follow-Up Timing Optimizer', category: 'Pipeline', description: 'Recommend follow-up timing by lead behavior.' },
  { id: 'fs-039', title: 'No-Show Recovery Planner', category: 'Pipeline', description: 'Recover no-shows with targeted rebooking plays.' },
  { id: 'fs-040', title: 'Lost-Reason Pattern Miner', category: 'Pipeline', description: 'Mine repeated reasons for closed-lost deals.' },

  { id: 'fs-041', title: 'Proposal Scope Consistency Check', category: 'Proposals', description: 'Validate scope language consistency across proposals.' },
  { id: 'fs-042', title: 'Proposal Margin Guardrail', category: 'Proposals', description: 'Warn when pricing drifts below margin targets.' },
  { id: 'fs-043', title: 'Deliverable Clarity Grader', category: 'Proposals', description: 'Ensure deliverables are concrete and measurable.' },
  { id: 'fs-044', title: 'Timeline Feasibility Validator', category: 'Proposals', description: 'Flag unrealistic timeline commitments.' },
  { id: 'fs-045', title: 'Upsell Opportunity Suggestor', category: 'Proposals', description: 'Suggest add-ons based on identified growth gaps.' },
  { id: 'fs-046', title: 'Terms Risk Detector', category: 'Proposals', description: 'Detect missing protections in proposal terms.' },
  { id: 'fs-047', title: 'Proposal Personalization Score', category: 'Proposals', description: 'Score personalization depth against client context.' },
  { id: 'fs-048', title: 'Follow-Up Sequence Composer', category: 'Proposals', description: 'Compose structured follow-up after proposal send.' },
  { id: 'fs-049', title: 'Decision Deadline Tracker', category: 'Proposals', description: 'Track proposal decision windows and reminders.' },
  { id: 'fs-050', title: 'Proposal Win-Loss Benchmarks', category: 'Proposals', description: 'Compare close rates by proposal type and segment.' },

  { id: 'fs-051', title: 'Cross-Channel Efficiency Matrix', category: 'Reporting', description: 'Compare output versus spend by channel.' },
  { id: 'fs-052', title: 'Anomaly Threshold Tuner', category: 'Reporting', description: 'Configure anomaly thresholds for KPI monitoring.' },
  { id: 'fs-053', title: 'Revenue Attribution Sandbox', category: 'Reporting', description: 'Model attribution scenarios and impact.' },
  { id: 'fs-054', title: 'Lagging Indicator Radar', category: 'Reporting', description: 'Surface metrics trailing early warning signs.' },
  { id: 'fs-055', title: 'Client KPI Narrative Builder', category: 'Reporting', description: 'Generate concise KPI narratives for client updates.' },
  { id: 'fs-056', title: 'Channel Blend Recommender', category: 'Reporting', description: 'Recommend better channel mix by outcomes.' },
  { id: 'fs-057', title: 'Forecast Drift Tracker', category: 'Reporting', description: 'Track forecast divergence over time.' },
  { id: 'fs-058', title: 'Pipeline-to-Revenue Waterfall', category: 'Reporting', description: 'Visualize pipeline conversion to realized revenue.' },
  { id: 'fs-059', title: 'Executive Snapshot Generator', category: 'Reporting', description: 'Build executive-ready summary snapshots quickly.' },
  { id: 'fs-060', title: 'Goal Variance Action Board', category: 'Reporting', description: 'Attach actions to KPI variance by owner.' },

  { id: 'fs-061', title: 'Onboarding Milestone Tracker', category: 'Client Ops', description: 'Track onboarding steps and completion risks.' },
  { id: 'fs-062', title: 'Asset Collection Queue', category: 'Client Ops', description: 'Collect required client assets with clear ownership.' },
  { id: 'fs-063', title: 'Approval Bottleneck Scanner', category: 'Client Ops', description: 'Detect approvals slowing campaign release.' },
  { id: 'fs-064', title: 'Communication Cadence Planner', category: 'Client Ops', description: 'Plan update cadence across account tiers.' },
  { id: 'fs-065', title: 'Renewal Health Index', category: 'Client Ops', description: 'Score retention risk using performance and sentiment.' },
  { id: 'fs-066', title: 'Expansion Readiness Meter', category: 'Client Ops', description: 'Measure readiness for upsell and expansion plays.' },
  { id: 'fs-067', title: 'Request Intake Triage Board', category: 'Client Ops', description: 'Triage inbound client requests by impact.' },
  { id: 'fs-068', title: 'Decision Log Timeline', category: 'Client Ops', description: 'Maintain account decision history and rationale.' },
  { id: 'fs-069', title: 'Scope Change Risk Monitor', category: 'Client Ops', description: 'Track out-of-scope risk before margin erosion.' },
  { id: 'fs-070', title: 'Client Success Plan Manager', category: 'Client Ops', description: 'Manage success plans tied to revenue goals.' },

  { id: 'fs-071', title: 'Topic Decay Watchlist', category: 'Content & SEO', description: 'Flag content losing search relevance.' },
  { id: 'fs-072', title: 'Keyword Intent Alignment Grid', category: 'Content & SEO', description: 'Align target keywords with conversion intent.' },
  { id: 'fs-073', title: 'Content Refresh Scheduler', category: 'Content & SEO', description: 'Schedule updates for aging content assets.' },
  { id: 'fs-074', title: 'SERP Competitor Gap Finder', category: 'Content & SEO', description: 'Identify gaps against top SERP competitors.' },
  { id: 'fs-075', title: 'Internal Linking Optimizer', category: 'Content & SEO', description: 'Improve topic authority via internal links.' },
  { id: 'fs-076', title: 'Local Landing Variant Planner', category: 'Content & SEO', description: 'Plan localized landing page variant coverage.' },
  { id: 'fs-077', title: 'Content ROI Tieback Board', category: 'Content & SEO', description: 'Tie content assets to pipeline outcomes.' },
  { id: 'fs-078', title: 'Cluster Authority Tracker', category: 'Content & SEO', description: 'Track authority growth by topic cluster.' },
  { id: 'fs-079', title: 'Search Brief Builder', category: 'Content & SEO', description: 'Generate brief outlines by search intent.' },
  { id: 'fs-080', title: 'Repurposing Queue Manager', category: 'Content & SEO', description: 'Queue assets for cross-channel repurposing.' },

  { id: 'fs-081', title: 'Lifecycle Nurture Planner', category: 'Automation', description: 'Plan nurture automations by lifecycle stage.' },
  { id: 'fs-082', title: 'Behavior Trigger Library', category: 'Automation', description: 'Maintain trigger templates for key user actions.' },
  { id: 'fs-083', title: 'Re-Engagement Sequence Builder', category: 'Automation', description: 'Create revive sequences for inactive leads.' },
  { id: 'fs-084', title: 'Channel Orchestration Board', category: 'Automation', description: 'Coordinate email, SMS, and retargeting cadences.' },
  { id: 'fs-085', title: 'Lead Routing Rule Simulator', category: 'Automation', description: 'Simulate routing logic before release.' },
  { id: 'fs-086', title: 'Alert Escalation Matrix', category: 'Automation', description: 'Set escalation paths for critical alerts.' },
  { id: 'fs-087', title: 'Workflow Failure Inspector', category: 'Automation', description: 'Track and resolve automation failures quickly.' },
  { id: 'fs-088', title: 'Consent State Orchestrator', category: 'Automation', description: 'Orchestrate consent-aware automations by state.' },
  { id: 'fs-089', title: 'Frequency Cap Manager', category: 'Automation', description: 'Protect audiences from message fatigue.' },
  { id: 'fs-090', title: 'Hand-off Summary Generator', category: 'Automation', description: 'Generate concise hand-off briefs for sales.' },

  { id: 'fs-091', title: 'Experiment Backlog Prioritizer', category: 'Experimentation', description: 'Prioritize experiments by impact and confidence.' },
  { id: 'fs-092', title: 'Test Design Canvas', category: 'Experimentation', description: 'Document hypothesis, metrics, and guardrails.' },
  { id: 'fs-093', title: 'Variant Coverage Checker', category: 'Experimentation', description: 'Ensure variant coverage across key segments.' },
  { id: 'fs-094', title: 'Sample Size Readiness Gauge', category: 'Experimentation', description: 'Estimate if tests have enough traffic to decide.' },
  { id: 'fs-095', title: 'Experiment Rollout Gate', category: 'Experimentation', description: 'Control launch gates before full rollout.' },
  { id: 'fs-096', title: 'Result Confidence Scorer', category: 'Experimentation', description: 'Score confidence in test outcomes.' },
  { id: 'fs-097', title: 'Post-Test Insight Library', category: 'Experimentation', description: 'Store learnings from completed tests.' },
  { id: 'fs-098', title: 'Winning Pattern Catalog', category: 'Experimentation', description: 'Catalog repeatable patterns that consistently win.' },
  { id: 'fs-099', title: 'Regression Risk Watcher', category: 'Experimentation', description: 'Watch for post-launch performance regressions.' },
  { id: 'fs-100', title: 'Quarterly Experiment Scorecard', category: 'Experimentation', description: 'Track experiment throughput and impact each quarter.' },
]
