import type { GrowthFeatureIdea } from '@/lib/growth-feature-ideas'

const implementedGrowthFeatureRoutes: Record<string, string> = {
  'Multi-Step Lead Capture Quiz': '/dashboard/agency-ops/lead-capture-quiz',
  'Progressive lead qualification forms': '/dashboard/agency-ops/progressive-qualification',
  'Dynamic scheduling widget for booked calls and demos': '/dashboard/agency-ops/dynamic-scheduling',
  'Geo-targeted landing page personalization': '/dashboard/agency-ops/geo-personalization',
  'Chat-based qualification flows for high-intent visitors': '/dashboard/agency-ops/chat-qualification',
  'Exit-Intent Offer Builder': '/dashboard/agency-ops/exit-intent-offers',
  'On-page rescue banner system': '/dashboard/agency-ops/rescue-banners',
  'Offer testing dashboard for pricing, guarantees, and hooks': '/dashboard/agency-ops/offer-testing',
  'Funnel drop-off analysis by step and page': '/dashboard/agency-ops/funnel-dropoff',
  'Call-to-action testing workspace': '/dashboard/agency-ops/cta-testing',
  'Pricing Sensitivity Tests': '/dashboard/agency-ops/pricing-sensitivity',
  'Lead scoring rules engine': '/dashboard/agency-ops/lead-scoring',
  'Pipeline SLA tracking for response-time accountability': '/dashboard/agency-ops/pipeline-sla',
  'Lost-deal reason analysis and objection tracking': '/dashboard/agency-ops/lost-deal-analysis',
  'Client Benchmark Scorecards': '/dashboard/agency-ops/benchmark-scorecards',
  'Executive KPI snapshot for clients': '/dashboard/agency-ops/executive-kpi',
  'Weekly wins and risks digest': '/dashboard/agency-ops/weekly-digest',
  'Forecast accuracy reporting': '/dashboard/agency-ops/forecast-accuracy',
  'Proposal Follow-Up Sequence Builder': '/dashboard/agency-ops/proposal-follow-up',
  'Instant lead routing to sales reps or inboxes': '/dashboard/agency-ops/lead-routing',
  'SMS opt-in capture for faster follow-up': '/dashboard/agency-ops/sms-opt-in',
  'Industry-specific intake form templates': '/dashboard/agency-ops/industry-intake',
  'Referral source and UTM auto-capture on every form': '/dashboard/agency-ops/attribution-capture',
  'Lead magnet library for gated assets and offers': '/dashboard/agency-ops/lead-magnets',
  'Form abandonment recovery workflows': '/dashboard/agency-ops/form-recovery',
  'Social proof block manager': '/dashboard/agency-ops/social-proof-blocks',
  'Lifecycle-specific callback sequences': '/dashboard/agency-ops/callback-sequences',
  'Response-time performance board': '/dashboard/agency-ops/response-time-board',
  'Micro-conversion prompt library': '/dashboard/agency-ops/micro-conversions',
  'Buyer objection prompt set': '/dashboard/agency-ops/buyer-objection-prompts',
  'Intent drift alerts for top landing pages': '/dashboard/agency-ops/intent-drift-alerts',
  'Conversion friction heatmap': '/dashboard/agency-ops/conversion-friction-heatmap',
  'Stale lead prioritization board': '/dashboard/agency-ops/stale-lead-board',
  'Client-ready anomaly summary generator': '/dashboard/agency-ops/anomaly-summaries',
  'Approval chase automation': '/dashboard/agency-ops/approval-chase',
  'Topic decay detector': '/dashboard/agency-ops/topic-decay',
  'Search query revenue map': '/dashboard/agency-ops/search-query-revenue',
  'Renewal countdown reminders': '/dashboard/agency-ops/renewal-countdown',
  'Reusable agency playbook library': '/dashboard/agency-ops/playbook-library',
  'Lead source confidence scoring': '/dashboard/agency-ops/source-confidence',
  'Progressive consent and compliance prompts': '/dashboard/agency-ops/consent-prompts',
  'Missed-call text-back automation': '/dashboard/agency-ops/missed-call-text',
  'Lead nurture workflows by funnel stage': '/dashboard/agency-ops/nurture-workflows',
  'Lead enrichment workflow queue': '/dashboard/agency-ops/lead-enrichment',
  'SEO opportunity scoring model': '/dashboard/agency-ops/seo-opportunity-scoring',
  'Topic cluster planner for SEO campaigns': '/dashboard/agency-ops/topic-cluster-planner',
  'Search intent brief generator for writers': '/dashboard/agency-ops/search-intent-briefs',
  'Local SEO landing page template system': '/dashboard/agency-ops/local-seo-templates',
  'Mobile conversion audit checklist': '/dashboard/agency-ops/mobile-audit',
  'Landing page to ad-message match scoring': '/dashboard/agency-ops/message-match',
  'Heatmap summary and click-pattern review': '/dashboard/agency-ops/heatmap-review',
  'Checkout friction detector for ecommerce and service flows': '/dashboard/agency-ops/checkout-friction',
  'Risk-reversal and guarantee section generator': '/dashboard/agency-ops/guarantee-sections',
  'Proof sequencing optimizer': '/dashboard/agency-ops/proof-sequencing',
  'Interactive proof comparison modules': '/dashboard/agency-ops/proof-comparison',
  'Page speed opportunity scanner tied to conversion impact': '/dashboard/agency-ops/page-speed-opportunities',
  'Offer packaging comparison workspace': '/dashboard/agency-ops/offer-packaging',
  'Sales handoff summaries generated from lead research': '/dashboard/agency-ops/sales-handoff',
  'Win-pattern analysis across industries and campaigns': '/dashboard/agency-ops/win-patterns',
  'Sales velocity benchmark board': '/dashboard/agency-ops/sales-velocity',
  'Opportunity aging heatmap': '/dashboard/agency-ops/opportunity-aging',
  'Deal health scores for active opportunities': '/dashboard/agency-ops/deal-health',
  'Persona tagging inside the CRM': '/dashboard/agency-ops/persona-tags',
  'Expansion and upsell opportunity tracking': '/dashboard/agency-ops/expansion-opportunities',
  'Lead source-to-revenue mapping': '/dashboard/agency-ops/source-revenue',
  'Portfolio benchmark anomaly alerts': '/dashboard/agency-ops/benchmark-alerts',
  'Goal variance alerts when KPIs slip': '/dashboard/agency-ops/goal-variance',
  'Lead quality trend reporting': '/dashboard/agency-ops/lead-quality-trends',
  'Content ROI reporting tied to pipeline': '/dashboard/agency-ops/content-roi',
  'Landing page leaderboard by conversion rate': '/dashboard/agency-ops/landing-page-leaderboard',
  'No-show recovery automations': '/dashboard/agency-ops/no-show-recovery',
  'Review request and testimonial collection automations': '/dashboard/agency-ops/review-automations',
  'Lead enrichment on form submission': '/dashboard/agency-ops/submission-enrichment',
  'Auto-reminders for client approvals and missing assets': '/dashboard/agency-ops/approval-reminders',
  'Content refresh opportunity finder': '/dashboard/agency-ops/content-refresh',
  'Competitor content gap analyzer': '/dashboard/agency-ops/content-gaps',
  'CTA consistency checker across blog and resource content': '/dashboard/agency-ops/cta-consistency',
  'Case study publishing workflow': '/dashboard/agency-ops/case-study-workflow',
  'Underperforming keyword alerts': '/dashboard/agency-ops/keyword-alerts',
  'Revenue per lead by campaign': '/dashboard/agency-ops/revenue-per-lead',
  'First-touch, last-touch, and multi-touch attribution views': '/dashboard/agency-ops/attribution-views',
  'Offline conversion import tracking': '/dashboard/agency-ops/offline-conversions',
  'Client request intake center': '/dashboard/agency-ops/request-center',
  'Cross-sell and upsell journey builder': '/dashboard/agency-ops/cross-sell-journeys',
  'Client-specific roadmap builder from Growth Hub ideas': '/dashboard/agency-ops/client-roadmap-builder',
  'Proposal add-ons generated from identified growth gaps': '/dashboard/agency-ops/proposal-addons',
  'Churn-risk dashboard for subscription clients': '/dashboard/agency-ops/churn-risk',
  'Post-purchase education and onboarding sequences': '/dashboard/agency-ops/post-purchase-sequences',
  'Retention milestone scorecards': '/dashboard/agency-ops/retention-scorecards',
  'Customer education content map': '/dashboard/agency-ops/customer-education',
  'Conversion lag analysis by campaign': '/dashboard/agency-ops/conversion-lag',
  'Budget reallocation recommendations': '/dashboard/agency-ops/budget-reallocation',
  'Audience overlap analyzer': '/dashboard/agency-ops/audience-overlap',
  'Retargeting sequence mapper': '/dashboard/agency-ops/retargeting-mapper',
  'Shared Growth Roadmap': '/dashboard/agency-ops/shared-roadmap',
  'Client onboarding checklist portal': '/dashboard/agency-ops/onboarding-portal',
  'Approval queue for ads, landing pages, and content': '/dashboard/agency-ops/approval-queue',
  'Client request intake workspace': '/dashboard/agency-ops/client-request-intake',
  'Monthly strategy recap generator': '/dashboard/agency-ops/strategy-recaps',
  'Customer Advocacy Score': '/dashboard/agency-ops/advocacy-score',
  'Client communication timeline': '/dashboard/agency-ops/communication-timeline',
  'Review and testimonial capture planner': '/dashboard/agency-ops/testimonial-capture',
  'Testimonial and proof asset manager': '/dashboard/agency-ops/proof-assets',
  'Win-back campaigns for former customers': '/dashboard/agency-ops/win-back-campaigns',
  'Success plans tied to revenue targets': '/dashboard/agency-ops/success-plans',
  'Reactivation queue for stale leads': '/dashboard/agency-ops/reactivation-queue',
  'Forecasted pipeline projection based on current lead flow': '/dashboard/agency-ops/pipeline-projection',
  'Client Cohort Retention Reporting': '/dashboard/agency-ops/cohort-retention',
  'Ad Testing Velocity Tracker': '/dashboard/agency-ops/ad-testing-velocity',
  'Referral Activation Campaigns': '/dashboard/agency-ops/referral-activation',
}

export function getGrowthFeatureRoute(feature: GrowthFeatureIdea) {
  return implementedGrowthFeatureRoutes[feature.title] ?? `/dashboard/growth-hub/${feature.id}`
}

export function isGrowthFeatureImplemented(feature: GrowthFeatureIdea) {
  return feature.title in implementedGrowthFeatureRoutes
}
