export type GrowthFeatureCategory =
  | 'Lead Capture'
  | 'Conversion'
  | 'CRM & Pipeline'
  | 'Reporting'
  | 'Automation'
  | 'Content & SEO'
  | 'Paid Media'
  | 'Client Experience'
  | 'Retention'
  | 'Attribution'

export type GrowthFeatureIdea = {
  id: string
  title: string
  category: GrowthFeatureCategory
  priority: 'High' | 'Medium' | 'Low'
  agencyValue: string
  clientOutcome: string
}

export const growthFeatureIdeasIntro = {
  title: 'Agency Growth Hub',
  description:
    'A curated bank of product ideas marketing agencies can use to help clients acquire, convert, retain, and expand revenue faster.',
}

export const growthFeatureIdeas: GrowthFeatureIdea[] = [
  {
    id: 'lead-capture-01',
    title: 'Multi-step lead capture quiz',
    category: 'Lead Capture',
    priority: 'High',
    agencyValue: 'Improves qualification before a salesperson reaches out.',
    clientOutcome: 'More qualified inquiries and higher form completion rates.',
  },
  {
    id: 'lead-capture-02',
    title: 'Exit-intent offer builder',
    category: 'Lead Capture',
    priority: 'High',
    agencyValue: 'Gives agencies a reusable play for recovering abandoning visitors.',
    clientOutcome: 'More leads from traffic that would otherwise bounce.',
  },
  {
    id: 'lead-capture-03',
    title: 'Geo-targeted landing page personalization',
    category: 'Lead Capture',
    priority: 'High',
    agencyValue: 'Makes campaigns more relevant without rebuilding pages manually.',
    clientOutcome: 'Better conversion rates in local and regional campaigns.',
  },
  {
    id: 'lead-capture-04',
    title: 'Dynamic call scheduling widget',
    category: 'Lead Capture',
    priority: 'High',
    agencyValue: 'Lets agencies drive booked meetings directly from campaigns.',
    clientOutcome: 'Shorter lead response time and more consultations booked.',
  },
  {
    id: 'lead-capture-05',
    title: 'Lead magnet library manager',
    category: 'Lead Capture',
    priority: 'Medium',
    agencyValue: 'Keeps offers organized by audience, stage, and campaign.',
    clientOutcome: 'More opt-ins across multiple funnel entry points.',
  },
  {
    id: 'lead-capture-06',
    title: 'Chat-first qualification flow',
    category: 'Lead Capture',
    priority: 'High',
    agencyValue: 'Creates a low-friction path for visitors who avoid forms.',
    clientOutcome: 'Higher engagement from mobile and high-intent visitors.',
  },
  {
    id: 'lead-capture-07',
    title: 'Referral source capture on every form',
    category: 'Lead Capture',
    priority: 'Medium',
    agencyValue: 'Improves campaign reporting without added admin work.',
    clientOutcome: 'Clear visibility into which channels drive pipeline.',
  },
  {
    id: 'lead-capture-08',
    title: 'Industry-specific intake templates',
    category: 'Lead Capture',
    priority: 'Medium',
    agencyValue: 'Speeds up deployment for agencies serving multiple niches.',
    clientOutcome: 'More relevant questions and cleaner sales handoff.',
  },
  {
    id: 'lead-capture-09',
    title: 'SMS opt-in capture module',
    category: 'Lead Capture',
    priority: 'Medium',
    agencyValue: 'Adds another owned audience channel agencies can monetize.',
    clientOutcome: 'Faster follow-up and stronger re-engagement potential.',
  },
  {
    id: 'lead-capture-10',
    title: 'Hidden field campaign tagging',
    category: 'Lead Capture',
    priority: 'Low',
    agencyValue: 'Makes attribution cleaner across landing pages and ads.',
    clientOutcome: 'Better understanding of which messages convert.',
  },
  {
    id: 'conversion-01',
    title: 'Offer testing workspace',
    category: 'Conversion',
    priority: 'High',
    agencyValue: 'Helps agencies compare hooks, guarantees, and pricing angles.',
    clientOutcome: 'Stronger landing page conversion performance.',
  },
  {
    id: 'conversion-02',
    title: 'Proof stack builder',
    category: 'Conversion',
    priority: 'High',
    agencyValue: 'Centralizes testimonials, stats, logos, and case studies.',
    clientOutcome: 'Greater buyer trust at critical decision moments.',
  },
  {
    id: 'conversion-03',
    title: 'Page speed opportunity scanner',
    category: 'Conversion',
    priority: 'Medium',
    agencyValue: 'Gives agencies a fast way to surface technical wins.',
    clientOutcome: 'Lower bounce rates and better ad efficiency.',
  },
  {
    id: 'conversion-04',
    title: 'Call-to-action heatmap summary',
    category: 'Conversion',
    priority: 'Medium',
    agencyValue: 'Shows where users hesitate before converting.',
    clientOutcome: 'More informed UX changes that lift conversion rate.',
  },
  {
    id: 'conversion-05',
    title: 'Funnel drop-off diagnosis',
    category: 'Conversion',
    priority: 'High',
    agencyValue: 'Helps agencies identify broken steps in the buyer journey.',
    clientOutcome: 'Higher completion rates across forms and checkouts.',
  },
  {
    id: 'conversion-06',
    title: 'Guarantee and risk-reversal block generator',
    category: 'Conversion',
    priority: 'Medium',
    agencyValue: 'Makes value proposition testing easier for client pages.',
    clientOutcome: 'Less buyer hesitation and more conversions.',
  },
  {
    id: 'conversion-07',
    title: 'Service page conversion checklist',
    category: 'Conversion',
    priority: 'Medium',
    agencyValue: 'Standardizes CRO reviews across client accounts.',
    clientOutcome: 'Consistent improvements to high-value landing pages.',
  },
  {
    id: 'conversion-08',
    title: 'Competitor offer comparison cards',
    category: 'Conversion',
    priority: 'Low',
    agencyValue: 'Supports sharper positioning in proposal and page copy.',
    clientOutcome: 'Clearer differentiation versus alternatives.',
  },
  {
    id: 'conversion-09',
    title: 'Mobile-first checkout audit',
    category: 'Conversion',
    priority: 'High',
    agencyValue: 'Surfaces conversion leaks that hit paid campaigns hard.',
    clientOutcome: 'More completed purchases and fewer abandoned carts.',
  },
  {
    id: 'conversion-10',
    title: 'Urgency and scarcity controls',
    category: 'Conversion',
    priority: 'Low',
    agencyValue: 'Lets agencies test ethical urgency patterns quickly.',
    clientOutcome: 'More decisive action from warm leads.',
  },
  {
    id: 'crm-pipeline-01',
    title: 'Lead scoring rules engine',
    category: 'CRM & Pipeline',
    priority: 'High',
    agencyValue: 'Prioritizes high-fit leads automatically.',
    clientOutcome: 'Sales teams spend time on leads most likely to close.',
  },
  {
    id: 'crm-pipeline-02',
    title: 'Pipeline stage SLA tracker',
    category: 'CRM & Pipeline',
    priority: 'High',
    agencyValue: 'Makes slow follow-up visible before revenue slips.',
    clientOutcome: 'Faster responses and improved close rates.',
  },
  {
    id: 'crm-pipeline-03',
    title: 'Lead source-to-revenue mapping',
    category: 'CRM & Pipeline',
    priority: 'High',
    agencyValue: 'Connects agency efforts directly to closed business.',
    clientOutcome: 'Better budgeting around channels that actually convert.',
  },
  {
    id: 'crm-pipeline-04',
    title: 'Lost deal reason analyzer',
    category: 'CRM & Pipeline',
    priority: 'Medium',
    agencyValue: 'Helps agencies see patterns behind failed opportunities.',
    clientOutcome: 'Better messaging, targeting, and objection handling.',
  },
  {
    id: 'crm-pipeline-05',
    title: 'Reactivation queue for stale leads',
    category: 'CRM & Pipeline',
    priority: 'High',
    agencyValue: 'Creates easy wins from dormant records already in the CRM.',
    clientOutcome: 'More pipeline without increasing acquisition spend.',
  },
  {
    id: 'crm-pipeline-06',
    title: 'Deal health scorecard',
    category: 'CRM & Pipeline',
    priority: 'Medium',
    agencyValue: 'Flags risky opportunities before they go cold.',
    clientOutcome: 'More predictable pipeline management.',
  },
  {
    id: 'crm-pipeline-07',
    title: 'Sales handoff summary generator',
    category: 'CRM & Pipeline',
    priority: 'Medium',
    agencyValue: 'Cuts down on manual summaries between marketing and sales.',
    clientOutcome: 'Cleaner context transfer and better close conversations.',
  },
  {
    id: 'crm-pipeline-08',
    title: 'Buyer persona tagging inside CRM',
    category: 'CRM & Pipeline',
    priority: 'Low',
    agencyValue: 'Improves segmentation for remarketing and nurture.',
    clientOutcome: 'More relevant follow-up across the funnel.',
  },
  {
    id: 'crm-pipeline-09',
    title: 'Account expansion opportunity tracker',
    category: 'CRM & Pipeline',
    priority: 'Medium',
    agencyValue: 'Supports agencies managing both acquisition and upsell.',
    clientOutcome: 'Higher customer lifetime value.',
  },
  {
    id: 'crm-pipeline-10',
    title: 'Win pattern dashboard',
    category: 'CRM & Pipeline',
    priority: 'Medium',
    agencyValue: 'Shows what winning opportunities have in common.',
    clientOutcome: 'Better focus on industries, offers, and messages that work.',
  },
  {
    id: 'reporting-01',
    title: 'Executive KPI snapshot',
    category: 'Reporting',
    priority: 'High',
    agencyValue: 'Makes client reporting faster and easier to present.',
    clientOutcome: 'Clear visibility into growth metrics without digging.',
  },
  {
    id: 'reporting-02',
    title: 'Weekly wins and risks digest',
    category: 'Reporting',
    priority: 'High',
    agencyValue: 'Turns account activity into a client-friendly narrative.',
    clientOutcome: 'More confidence in what is working and what needs attention.',
  },
  {
    id: 'reporting-03',
    title: 'Campaign pacing monitor',
    category: 'Reporting',
    priority: 'Medium',
    agencyValue: 'Prevents underspend or overspend surprises.',
    clientOutcome: 'More stable campaign delivery and lead flow.',
  },
  {
    id: 'reporting-04',
    title: 'Goal variance alerts',
    category: 'Reporting',
    priority: 'High',
    agencyValue: 'Lets agencies intervene quickly when performance dips.',
    clientOutcome: 'Faster course correction and less wasted budget.',
  },
  {
    id: 'reporting-05',
    title: 'Cross-channel performance scoreboard',
    category: 'Reporting',
    priority: 'High',
    agencyValue: 'Unifies ad, email, SEO, and outbound performance.',
    clientOutcome: 'Smarter channel mix decisions.',
  },
  {
    id: 'reporting-06',
    title: 'Landing page leaderboard',
    category: 'Reporting',
    priority: 'Medium',
    agencyValue: 'Highlights which pages deserve more budget or iteration.',
    clientOutcome: 'Faster scaling of winning pages.',
  },
  {
    id: 'reporting-07',
    title: 'Content ROI tracker',
    category: 'Reporting',
    priority: 'Medium',
    agencyValue: 'Proves the value of SEO and content retainer work.',
    clientOutcome: 'Better investment in content that drives pipeline.',
  },
  {
    id: 'reporting-08',
    title: 'Lead quality trend report',
    category: 'Reporting',
    priority: 'Medium',
    agencyValue: 'Separates volume wins from actual revenue wins.',
    clientOutcome: 'Higher quality acquisition over time.',
  },
  {
    id: 'reporting-09',
    title: 'Creative fatigue warning system',
    category: 'Reporting',
    priority: 'Medium',
    agencyValue: 'Helps agencies refresh ads before they burn out.',
    clientOutcome: 'More efficient ad spend and steadier lead flow.',
  },
  {
    id: 'reporting-10',
    title: 'Forecasted pipeline projection',
    category: 'Reporting',
    priority: 'High',
    agencyValue: 'Turns current campaign activity into a business planning signal.',
    clientOutcome: 'More confidence in hiring, inventory, and budget decisions.',
  },
  {
    id: 'automation-01',
    title: 'Instant lead routing rules',
    category: 'Automation',
    priority: 'High',
    agencyValue: 'Removes manual assignment work across teams and regions.',
    clientOutcome: 'Faster first touch and better lead ownership.',
  },
  {
    id: 'automation-02',
    title: 'Missed call text-back automation',
    category: 'Automation',
    priority: 'High',
    agencyValue: 'Captures leads even when the client misses the call.',
    clientOutcome: 'More recovered opportunities and booked callbacks.',
  },
  {
    id: 'automation-03',
    title: 'Proposal follow-up sequence builder',
    category: 'Automation',
    priority: 'High',
    agencyValue: 'Standardizes follow-up after agencies send proposals.',
    clientOutcome: 'More proposals turning into signed deals.',
  },
  {
    id: 'automation-04',
    title: 'Lead nurture journey templates',
    category: 'Automation',
    priority: 'High',
    agencyValue: 'Lets agencies launch retention and nurture flows faster.',
    clientOutcome: 'More conversions from not-yet-ready leads.',
  },
  {
    id: 'automation-05',
    title: 'No-show recovery workflow',
    category: 'Automation',
    priority: 'Medium',
    agencyValue: 'Turns missed appointments into a repeatable recovery system.',
    clientOutcome: 'More booked meetings recovered without manual chasing.',
  },
  {
    id: 'automation-06',
    title: 'Review request automation',
    category: 'Automation',
    priority: 'Medium',
    agencyValue: 'Feeds social proof programs automatically.',
    clientOutcome: 'More positive reviews and improved trust signals.',
  },
  {
    id: 'automation-07',
    title: 'High-intent page visit alerts',
    category: 'Automation',
    priority: 'Medium',
    agencyValue: 'Notifies sales teams when buyers show strong purchase intent.',
    clientOutcome: 'Faster outreach to warm prospects.',
  },
  {
    id: 'automation-08',
    title: 'Form abandonment rescue emails',
    category: 'Automation',
    priority: 'Medium',
    agencyValue: 'Adds a recovery mechanism to existing funnels.',
    clientOutcome: 'More completions from partially interested visitors.',
  },
  {
    id: 'automation-09',
    title: 'Auto-generated client task reminders',
    category: 'Automation',
    priority: 'Low',
    agencyValue: 'Reduces project delays caused by missing client inputs.',
    clientOutcome: 'Campaigns launch faster and stay on schedule.',
  },
  {
    id: 'automation-10',
    title: 'Lead enrichment on submission',
    category: 'Automation',
    priority: 'High',
    agencyValue: 'Saves research time immediately after a lead arrives.',
    clientOutcome: 'Sales gets better context before outreach starts.',
  },
  {
    id: 'content-seo-01',
    title: 'Topic cluster planner',
    category: 'Content & SEO',
    priority: 'High',
    agencyValue: 'Helps agencies build scalable content strategies by intent.',
    clientOutcome: 'Stronger organic visibility around money terms.',
  },
  {
    id: 'content-seo-02',
    title: 'Search intent brief generator',
    category: 'Content & SEO',
    priority: 'High',
    agencyValue: 'Speeds up content briefing for writers and strategists.',
    clientOutcome: 'Better alignment between content and buyer questions.',
  },
  {
    id: 'content-seo-03',
    title: 'Local SEO landing page templates',
    category: 'Content & SEO',
    priority: 'Medium',
    agencyValue: 'Makes multi-location growth easier to execute.',
    clientOutcome: 'More local search visibility and local leads.',
  },
  {
    id: 'content-seo-04',
    title: 'Content refresh opportunity finder',
    category: 'Content & SEO',
    priority: 'Medium',
    agencyValue: 'Finds quick SEO wins inside existing assets.',
    clientOutcome: 'Traffic and leads grow without publishing from scratch.',
  },
  {
    id: 'content-seo-05',
    title: 'Schema markup recommendation engine',
    category: 'Content & SEO',
    priority: 'Low',
    agencyValue: 'Helps agencies improve SERP visibility with lower effort.',
    clientOutcome: 'Better click-through rates from organic search.',
  },
  {
    id: 'content-seo-06',
    title: 'Case study publishing pipeline',
    category: 'Content & SEO',
    priority: 'Medium',
    agencyValue: 'Turns client wins into repeatable sales assets.',
    clientOutcome: 'More trust-building content to support conversions.',
  },
  {
    id: 'content-seo-07',
    title: 'Lead magnet content repurposer',
    category: 'Content & SEO',
    priority: 'Low',
    agencyValue: 'Extends the value of each major content asset.',
    clientOutcome: 'More reach from existing thought leadership.',
  },
  {
    id: 'content-seo-08',
    title: 'Competitor content gap analyzer',
    category: 'Content & SEO',
    priority: 'Medium',
    agencyValue: 'Surfaces under-served topics worth attacking.',
    clientOutcome: 'Better chance to win traffic in strategic areas.',
  },
  {
    id: 'content-seo-09',
    title: 'On-page CTA consistency checker',
    category: 'Content & SEO',
    priority: 'Low',
    agencyValue: 'Makes sure content assets actually convert traffic.',
    clientOutcome: 'Higher lead yield from blog and resource pages.',
  },
  {
    id: 'content-seo-10',
    title: 'SEO opportunity scoring model',
    category: 'Content & SEO',
    priority: 'High',
    agencyValue: 'Helps prioritize content effort by business value.',
    clientOutcome: 'Faster return from organic growth investments.',
  },
  {
    id: 'paid-media-01',
    title: 'Creative testing tracker',
    category: 'Paid Media',
    priority: 'High',
    agencyValue: 'Keeps ad learning organized across accounts and campaigns.',
    clientOutcome: 'Faster improvement in cost per lead and conversion rate.',
  },
  {
    id: 'paid-media-02',
    title: 'Audience overlap analyzer',
    category: 'Paid Media',
    priority: 'Medium',
    agencyValue: 'Prevents waste caused by competing audience segments.',
    clientOutcome: 'More efficient paid spend.',
  },
  {
    id: 'paid-media-03',
    title: 'Budget reallocation recommendations',
    category: 'Paid Media',
    priority: 'High',
    agencyValue: 'Supports smarter channel and campaign budget shifts.',
    clientOutcome: 'Better returns from the same budget.',
  },
  {
    id: 'paid-media-04',
    title: 'Lead quality by ad set reporting',
    category: 'Paid Media',
    priority: 'High',
    agencyValue: 'Stops teams from scaling low-quality lead sources.',
    clientOutcome: 'Paid campaigns produce better-fit opportunities.',
  },
  {
    id: 'paid-media-05',
    title: 'Retargeting sequence map',
    category: 'Paid Media',
    priority: 'Medium',
    agencyValue: 'Helps agencies align messaging to intent depth.',
    clientOutcome: 'More conversions from returning visitors.',
  },
  {
    id: 'paid-media-06',
    title: 'Offer-to-audience matching dashboard',
    category: 'Paid Media',
    priority: 'Medium',
    agencyValue: 'Improves message-market fit inside paid campaigns.',
    clientOutcome: 'Higher relevance and lower acquisition costs.',
  },
  {
    id: 'paid-media-07',
    title: 'Ad copy angle generator',
    category: 'Paid Media',
    priority: 'Low',
    agencyValue: 'Speeds up new test creation for paid teams.',
    clientOutcome: 'More creative variation and learning velocity.',
  },
  {
    id: 'paid-media-08',
    title: 'Landing page to ad message match score',
    category: 'Paid Media',
    priority: 'Medium',
    agencyValue: 'Finds disconnects that hurt Quality Score and conversion.',
    clientOutcome: 'Better ad efficiency and post-click performance.',
  },
  {
    id: 'paid-media-09',
    title: 'Underperforming keyword alerting',
    category: 'Paid Media',
    priority: 'Medium',
    agencyValue: 'Cuts wasted spend sooner in search campaigns.',
    clientOutcome: 'More budget directed to profitable queries.',
  },
  {
    id: 'paid-media-10',
    title: 'Creative fatigue renewal queue',
    category: 'Paid Media',
    priority: 'Low',
    agencyValue: 'Keeps ad refreshes on pace without spreadsheet chasing.',
    clientOutcome: 'More stable campaign performance over time.',
  },
  {
    id: 'client-experience-01',
    title: 'Client onboarding checklist portal',
    category: 'Client Experience',
    priority: 'High',
    agencyValue: 'Standardizes launch operations for every account.',
    clientOutcome: 'Faster time to value after signing.',
  },
  {
    id: 'client-experience-02',
    title: 'Approval queue for ads and pages',
    category: 'Client Experience',
    priority: 'Medium',
    agencyValue: 'Reduces revision chaos and missed approvals.',
    clientOutcome: 'Campaigns move live with less delay.',
  },
  {
    id: 'client-experience-03',
    title: 'Shared growth roadmap',
    category: 'Client Experience',
    priority: 'High',
    agencyValue: 'Keeps agencies and clients aligned on next priorities.',
    clientOutcome: 'Clearer expectations and better strategic momentum.',
  },
  {
    id: 'client-experience-04',
    title: 'Monthly strategy recap generator',
    category: 'Client Experience',
    priority: 'Medium',
    agencyValue: 'Turns execution into an understandable client update.',
    clientOutcome: 'Better trust and retention.',
  },
  {
    id: 'client-experience-05',
    title: 'Launch readiness score',
    category: 'Client Experience',
    priority: 'Low',
    agencyValue: 'Highlights blockers before campaigns start.',
    clientOutcome: 'Smoother go-lives and fewer last-minute issues.',
  },
  {
    id: 'client-experience-06',
    title: 'Client request intake center',
    category: 'Client Experience',
    priority: 'Medium',
    agencyValue: 'Centralizes asks that otherwise arrive by email and chat.',
    clientOutcome: 'Faster turnaround and fewer missed requests.',
  },
  {
    id: 'client-experience-07',
    title: 'Performance milestone celebrations',
    category: 'Client Experience',
    priority: 'Low',
    agencyValue: 'Creates moments that reinforce agency value.',
    clientOutcome: 'Stronger client confidence and loyalty.',
  },
  {
    id: 'client-experience-08',
    title: 'Meeting agenda auto-builder',
    category: 'Client Experience',
    priority: 'Low',
    agencyValue: 'Cuts prep time for recurring account calls.',
    clientOutcome: 'More useful strategy meetings with less admin.',
  },
  {
    id: 'client-experience-09',
    title: 'Success plan by business goal',
    category: 'Client Experience',
    priority: 'High',
    agencyValue: 'Keeps work tied to client outcomes, not random tasks.',
    clientOutcome: 'More strategic progress toward revenue goals.',
  },
  {
    id: 'client-experience-10',
    title: 'Client portal health snapshot',
    category: 'Client Experience',
    priority: 'Medium',
    agencyValue: 'Gives clients a quick self-serve view of momentum.',
    clientOutcome: 'Less confusion and more visibility between meetings.',
  },
  {
    id: 'retention-01',
    title: 'Customer onboarding nurture flow',
    category: 'Retention',
    priority: 'High',
    agencyValue: 'Extends agency value beyond acquisition into retention.',
    clientOutcome: 'Better activation and reduced churn risk.',
  },
  {
    id: 'retention-02',
    title: 'Churn risk signal dashboard',
    category: 'Retention',
    priority: 'High',
    agencyValue: 'Lets agencies spot retention issues early for subscription clients.',
    clientOutcome: 'Improved retention and lifetime value.',
  },
  {
    id: 'retention-03',
    title: 'Cross-sell journey builder',
    category: 'Retention',
    priority: 'Medium',
    agencyValue: 'Supports expansion revenue programs for existing customers.',
    clientOutcome: 'Higher average order value and account value.',
  },
  {
    id: 'retention-04',
    title: 'Renewal reminder campaigns',
    category: 'Retention',
    priority: 'Medium',
    agencyValue: 'Automates an important but often-forgotten retention motion.',
    clientOutcome: 'More renewals and fewer accidental churns.',
  },
  {
    id: 'retention-05',
    title: 'Customer win-back segments',
    category: 'Retention',
    priority: 'Medium',
    agencyValue: 'Creates a repeatable path for recovering lost customers.',
    clientOutcome: 'More reactivated accounts from the existing base.',
  },
  {
    id: 'retention-06',
    title: 'NPS follow-up workflows',
    category: 'Retention',
    priority: 'Low',
    agencyValue: 'Turns feedback data into action instead of just reporting.',
    clientOutcome: 'Happier customers and more referral potential.',
  },
  {
    id: 'retention-07',
    title: 'Usage milestone messaging',
    category: 'Retention',
    priority: 'Low',
    agencyValue: 'Helps reinforce product value after purchase.',
    clientOutcome: 'Higher engagement and stronger product adoption.',
  },
  {
    id: 'retention-08',
    title: 'VIP customer segment builder',
    category: 'Retention',
    priority: 'Low',
    agencyValue: 'Supports loyalty and advocacy programs for top customers.',
    clientOutcome: 'More repeat business and referrals.',
  },
  {
    id: 'retention-09',
    title: 'Replenishment reminder campaigns',
    category: 'Retention',
    priority: 'Medium',
    agencyValue: 'Useful for agencies serving ecommerce and subscription brands.',
    clientOutcome: 'More repeat purchases at the right time.',
  },
  {
    id: 'retention-10',
    title: 'Post-purchase education sequences',
    category: 'Retention',
    priority: 'Medium',
    agencyValue: 'Improves onboarding for complex products and services.',
    clientOutcome: 'Better retention through faster customer success.',
  },
  {
    id: 'attribution-01',
    title: 'First-touch and last-touch reporting',
    category: 'Attribution',
    priority: 'High',
    agencyValue: 'Gives clients a clearer channel value story.',
    clientOutcome: 'Better strategic investment decisions.',
  },
  {
    id: 'attribution-02',
    title: 'Multi-touch conversion paths',
    category: 'Attribution',
    priority: 'High',
    agencyValue: 'Shows how channels support each other before conversion.',
    clientOutcome: 'More accurate budget allocation across the funnel.',
  },
  {
    id: 'attribution-03',
    title: 'Offline conversion import tracker',
    category: 'Attribution',
    priority: 'Medium',
    agencyValue: 'Brings sales outcomes back into campaign optimization.',
    clientOutcome: 'Ad platforms optimize toward real revenue, not just leads.',
  },
  {
    id: 'attribution-04',
    title: 'Call tracking source breakdown',
    category: 'Attribution',
    priority: 'Medium',
    agencyValue: 'Useful for local and service businesses that close by phone.',
    clientOutcome: 'Better visibility into which campaigns drive calls.',
  },
  {
    id: 'attribution-05',
    title: 'Landing page assisted conversion report',
    category: 'Attribution',
    priority: 'Low',
    agencyValue: 'Shows pages that influence conversions even if they are not the final touch.',
    clientOutcome: 'Smarter optimization of supporting content.',
  },
  {
    id: 'attribution-06',
    title: 'UTM governance checker',
    category: 'Attribution',
    priority: 'Low',
    agencyValue: 'Catches messy tracking setups before reporting breaks.',
    clientOutcome: 'Cleaner campaign data and fewer blind spots.',
  },
  {
    id: 'attribution-07',
    title: 'Campaign naming convention enforcer',
    category: 'Attribution',
    priority: 'Low',
    agencyValue: 'Makes account reporting easier as agency teams scale.',
    clientOutcome: 'More consistent analytics and easier troubleshooting.',
  },
  {
    id: 'attribution-08',
    title: 'Channel incrementality notes',
    category: 'Attribution',
    priority: 'Medium',
    agencyValue: 'Encourages smarter analysis beyond platform-reported conversions.',
    clientOutcome: 'Better decisions about where marketing actually creates lift.',
  },
  {
    id: 'attribution-09',
    title: 'Sales cycle length by source',
    category: 'Attribution',
    priority: 'Medium',
    agencyValue: 'Shows which channels bring fast-closing versus long-cycle leads.',
    clientOutcome: 'More realistic forecasting and channel planning.',
  },
  {
    id: 'attribution-10',
    title: 'Revenue per lead by campaign',
    category: 'Attribution',
    priority: 'High',
    agencyValue: 'Elevates agency reporting from volume to profitability.',
    clientOutcome: 'Focus on campaigns that create the best revenue outcomes.',
  },
]

export const growthFeatureCategories = Array.from(
  new Set(growthFeatureIdeas.map((feature) => feature.category))
)

export const growthFeaturePriorityCounts = growthFeatureIdeas.reduce<Record<string, number>>(
  (acc, feature) => {
    acc[feature.priority] = (acc[feature.priority] ?? 0) + 1
    return acc
  },
  {}
)
