'use client'

import { useState } from 'react'
import { Bot, Loader2, Sparkles, RefreshCw } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'

interface Lead {
  company: string
  status: string
  lead_quality?: string | null
  estimated_revenue?: number | null
  acquisition_channel?: string | null
}

export function ReportingAISummary({ leads }: { leads: Lead[] }) {
  const [summary, setSummary] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [model, setModel] = useState('')

  async function generateSummary() {
    setLoading(true)
    setError('')
    setSummary('')

    let selectedModel = model
    if (!selectedModel) {
      try {
        const s = await fetch('/api/ollama/status').then(r => r.json())
        selectedModel = s.models?.[0] ?? 'llama3'
        setModel(selectedModel)
      } catch {
        selectedModel = 'llama3'
      }
    }

    try {
      const res = await fetch('/api/ollama/analyze-pipeline', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ leads, model: selectedModel, mode: 'summary' }),
      })
      const data = await res.json()
      if (!res.ok) { setError(data.error ?? 'Failed'); return }
      setSummary(data.summary)
    } catch {
      setError('Could not reach Ollama')
    } finally {
      setLoading(false)
    }
  }

  return (
    <Card className="border-primary/20">
      <CardHeader className="flex flex-row items-center justify-between pb-3">
        <CardTitle className="text-base flex items-center gap-2">
          <Bot className="h-4 w-4 text-primary" />
          AI Executive Summary
        </CardTitle>
        <Button size="sm" variant="outline" onClick={generateSummary} disabled={loading || leads.length === 0} className="gap-1.5">
          {loading
            ? <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Summarizing...</>
            : summary
              ? <><RefreshCw className="h-3.5 w-3.5" /> Refresh</>
              : <><Sparkles className="h-3.5 w-3.5" /> Generate Summary</>}
        </Button>
      </CardHeader>
      <CardContent>
        {!summary && !loading && !error && (
          <p className="text-sm text-muted-foreground">
            Generate an Ollama-powered plain-English summary of your current pipeline for stakeholder reporting.
          </p>
        )}
        {error && <p className="text-sm text-destructive">{error}</p>}
        {summary && (
          <div className="space-y-2">
            <p className="text-sm leading-relaxed">{summary}</p>
            {model && <p className="text-xs text-muted-foreground text-right">Generated by {model}</p>}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
